run:
  issues-exit-code: 0
  output:
    sort-results: true
linters:
  disable-all: true
  enable:
    - lll
    - godox
    - gochecknoinits
    - gosec
    - gocritic
    # - wsl
linters-settings:
  lll:
    line-length: 120
